language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
- chmod a+x ./Travis/installUnity.sh
install:
- ./Travis/installUnity.sh
before_script:
- chmod a+x ./Travis/getSDK.sh
- chmod a+x ./Travis/runTests.sh
script:
- ./Travis/getSDK.sh
- travis_wait 15 ./Travis/runTests.sh
